import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      	<Head>
       		<title>LearnNext</title>
        	<meta name="description" content="Generated by create next app" />
        	<meta name="viewport" content="width=device-width, initial-scale=1" />
        	<link rel="icon" href="/favicon.ico" />
      	</Head>
      	<div className='bg-slate-50 flex sm:flex-col md:flex-row items-center justify-around min-h-screen'>
		  	<Link href="/create">
			<div className='bg-orange-300 rounded-md md:py-40 md:px-56 text-center text-5xl '>
				<span>
					Create
				</span>
			</div>
			</Link>

			<Link href="/learn">
			<div className='bg-orange-300 rounded-md md:py-40 md:px-56 text-center text-5xl '>
				<span>
					Learn
				</span>
			</div>
			</Link>
      	</div>
    </>
  )
}
