import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Learn() {
  return (
    <>
      	<Head>
       		<title>LearnNext</title>
        	<meta name="description" content="Generated by create next app" />
        	<meta name="viewport" content="width=device-width, initial-scale=1" />
        	<link rel="icon" href="/favicon.ico" />
      	</Head>
      	<div className='bg-slate-50 flex items-center justify-around min-h-screen'>
			<div className='bg-orange-300 py-40 px-56 text-center text-5xl '>
				<span>
					Learn
				</span>
			</div>
      	</div>
    </>
  )
}
